/**
 * Service to handle file exports (PDF, Word, HTML, Markdown).
 */

export class ExportService {
  /**
   * Helper to trigger a browser file download.
   */
  static downloadFile(content, mimeType, filename) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Exports the markdown content as a .md file.
   */
  static exportMarkdown(markdownText, filename = 'HR_Analytics_AI_Report.md') {
    this.downloadFile(markdownText, 'text/markdown;charset=utf-8', filename);
  }

  /**
   * Exports markdown as a beautifully styled standalone HTML file.
   */
  static exportHtml(markdownText, filename = 'HR_Analytics_AI_Report.html') {
    const htmlContent = this.convertMarkdownToHtml(markdownText);
    const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HR Analytics Executive Report</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body { font-family: 'Inter', sans-serif; background-color: #f8fafc; color: #1e293b; }
    .report-container { max-width: 800px; margin: 40px auto; padding: 40px; background: white; border-radius: 16px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06); }
    h1 { font-size: 2.25rem; font-weight: 800; color: #1e3a8a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-top: 2rem; margin-bottom: 1.5rem; }
    h2 { font-size: 1.5rem; font-weight: 700; color: #2563eb; margin-top: 2rem; margin-bottom: 1rem; }
    h3 { font-size: 1.25rem; font-weight: 600; color: #1d4ed8; margin-top: 1.5rem; margin-bottom: 0.75rem; }
    p { margin-bottom: 1rem; line-height: 1.7; font-size: 1rem; color: #334155; }
    ul, ol { margin-left: 1.5rem; margin-bottom: 1rem; list-style-type: disc; color: #334155; }
    li { margin-bottom: 0.5rem; line-height: 1.5; }
    blockquote { border-left: 4px solid #cbd5e1; padding-left: 16px; color: #475569; font-style: italic; margin: 1.5rem 0; }
    table { width: 100%; border-collapse: collapse; margin: 1.5rem 0; font-size: 0.875rem; }
    th, td { border: 1px solid #e2e8f0; padding: 10px 12px; text-align: left; }
    th { background-color: #f1f5f9; font-weight: 600; color: #1e293b; }
    tr:nth-child(even) { background-color: #f8fafc; }
  </style>
</head>
<body>
  <div class="report-container">
    <div class="text-right text-xs text-slate-400 mb-6">Generated by Antigravity HR Insights on ${new Date().toLocaleDateString()}</div>
    ${htmlContent}
  </div>
</body>
</html>`;

    this.downloadFile(fullHtml, 'text/html;charset=utf-8', filename);
  }

  /**
   * Exports markdown as a Word document (.doc format using HTML-MSWord compatibility).
   */
  static exportWord(markdownText, filename = 'HR_Analytics_AI_Report.doc') {
    const htmlContent = this.convertMarkdownToHtml(markdownText);
    
    // MS Word understands HTML files with special Office schemas
    const wordContent = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head>
  <title>HR Analytics Report</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    body { font-family: 'Calibri', 'Arial', sans-serif; line-height: 1.5; color: #333333; }
    h1 { color: #1e3a8a; font-size: 22pt; font-weight: bold; border-bottom: 2px solid #dddddd; padding-bottom: 5px; margin-top: 24pt; margin-bottom: 12pt; }
    h2 { color: #2563eb; font-size: 16pt; font-weight: bold; margin-top: 18pt; margin-bottom: 8pt; border-bottom: 1px solid #eeeeee; }
    h3 { color: #1d4ed8; font-size: 13pt; font-weight: bold; margin-top: 14pt; margin-bottom: 6pt; }
    p { font-size: 11pt; margin-bottom: 10pt; text-align: justify; }
    ul { list-style-type: disc; margin-left: 20pt; margin-bottom: 10pt; }
    ol { list-style-type: decimal; margin-left: 20pt; margin-bottom: 10pt; }
    li { font-size: 11pt; margin-bottom: 4pt; }
    blockquote { border-left: 3pt solid #cbd5e1; padding-left: 10pt; color: #555555; font-style: italic; margin-top: 10pt; margin-bottom: 10pt; }
    table { border-collapse: collapse; width: 100%; margin-top: 12pt; margin-bottom: 12pt; }
    th, td { border: 1px solid #cccccc; padding: 6pt 8pt; text-align: left; font-size: 10pt; }
    th { background-color: #f3f4f6; font-weight: bold; color: #111111; }
  </style>
</head>
<body>
  <div style="margin: 1in;">
    <p style="text-align: right; font-size: 9pt; color: #888888;">Generated by Antigravity HR Insights • ${new Date().toLocaleDateString()}</p>
    ${htmlContent}
  </div>
</body>
</html>`;

    this.downloadFile(wordContent, 'application/msword;charset=utf-8', filename);
  }

  /**
   * Triggers the PDF download of a specific DOM element using html2pdf.js.
   */
  static exportPdf(elementId, filename = 'HR_Analytics_AI_Report.pdf') {
    const element = document.getElementById(elementId);
    if (!element) {
      console.error(`Element with id ${elementId} not found.`);
      return;
    }

    const opt = {
      margin:       [15, 15, 15, 15],
      filename:     filename,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true, logging: false },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] }
    };

    // Use standard window.html2pdf if loaded via CDN
    if (window.html2pdf) {
      window.html2pdf().set(opt).from(element).save();
    } else {
      console.error("html2pdf library is not loaded.");
      alert("PDF library failed to load. Please try printing via your browser (Ctrl+P / Cmd+P).");
    }
  }

  /**
   * Minimalistic line-by-line Markdown-to-HTML parser.
   */
  static convertMarkdownToHtml(md) {
    if (!md) return '';

    const lines = md.split('\n');
    let html = [];
    let inList = false;
    let listType = null; // 'ul' or 'ol'
    let inTable = false;
    let tableHeaders = [];
    let tableRows = [];

    for (let i = 0; i < lines.length; i++) {
      let line = lines[i].trim();

      // Close table if line is empty or doesn't start with |
      if (inTable && (!line || !line.startsWith('|'))) {
        html.push(this.renderHtmlTable(tableHeaders, tableRows));
        inTable = false;
        tableHeaders = [];
        tableRows = [];
      }

      // Close list if line is not a list item
      const isListItem = line.startsWith('- ') || line.startsWith('* ') || /^\d+\.\s/.test(line);
      if (inList && !isListItem && line !== '') {
        html.push(`</${listType}>`);
        inList = false;
        listType = null;
      }

      if (!line) {
        if (!inTable && !inList) {
          // Empty line, do nothing or break paragraph
        }
        continue;
      }

      // Headers
      if (line.startsWith('# ')) {
        html.push(`<h1>${this.parseInline(line.substring(2))}</h1>`);
      } else if (line.startsWith('## ')) {
        html.push(`<h2>${this.parseInline(line.substring(3))}</h2>`);
      } else if (line.startsWith('### ')) {
        html.push(`<h3>${this.parseInline(line.substring(4))}</h3>`);
      } 
      // Blockquotes
      else if (line.startsWith('> ')) {
        html.push(`<blockquote>${this.parseInline(line.substring(2))}</blockquote>`);
      }
      // Table Row
      else if (line.startsWith('|')) {
        const cells = line.split('|').map(c => c.trim()).filter((c, idx, arr) => idx > 0 && idx < arr.length - 1);
        
        // Ignore separator lines (e.g. |---|---|)
        if (cells.every(c => /^:?-+:?$/.test(c))) {
          continue; 
        }

        if (!inTable) {
          inTable = true;
          tableHeaders = cells;
        } else {
          tableRows.push(cells);
        }
      }
      // Unordered Lists
      else if (line.startsWith('- ') || line.startsWith('* ')) {
        if (!inList || listType !== 'ul') {
          if (inList) html.push(`</${listType}>`);
          html.push('<ul>');
          inList = true;
          listType = 'ul';
        }
        html.push(`<li>${this.parseInline(line.substring(2))}</li>`);
      }
      // Ordered Lists
      else if (/^\d+\.\s/.test(line)) {
        const match = line.match(/^(\d+)\.\s(.*)/);
        if (!inList || listType !== 'ol') {
          if (inList) html.push(`</${listType}>`);
          html.push('<ol>');
          inList = true;
          listType = 'ol';
        }
        html.push(`<li>${this.parseInline(match[2])}</li>`);
      }
      // Plain Paragraphs
      else {
        html.push(`<p>${this.parseInline(line)}</p>`);
      }
    }

    // Wrap up open tags
    if (inTable) {
      html.push(this.renderHtmlTable(tableHeaders, tableRows));
    }
    if (inList) {
      html.push(`</${listType}>`);
    }

    return html.join('\n');
  }

  /**
   * Utility to parse inline markdown elements: bold, italic, code.
   */
  static parseInline(text) {
    let clean = text;
    // HTML escape
    clean = clean
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

    // Bold (**text** or __text__)
    clean = clean.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    clean = clean.replace(/__(.*?)__/g, '<strong>$1</strong>');

    // Italic (*text* or _text_)
    clean = clean.replace(/\*(.*?)\*/g, '<em>$1</em>');
    clean = clean.replace(/_(.*?)_/g, '<em>$1</em>');

    // Inline Code (`code`)
    clean = clean.replace(/`(.*?)`/g, '<code class="bg-slate-100 text-rose-600 px-1 py-0.5 rounded font-mono text-xs">$1</code>');

    return clean;
  }

  /**
   * Helper to build a table HTML string.
   */
  static renderHtmlTable(headers, rows) {
    let html = '<table>';
    html += '<thead><tr>';
    headers.forEach(h => {
      html += `<th>${this.parseInline(h)}</th>`;
    });
    html += '</tr></thead>';
    html += '<tbody>';
    rows.forEach(row => {
      html += '<tr>';
      row.forEach(cell => {
        html += `<td>${this.parseInline(cell)}</td>`;
      });
      html += '</tr>';
    });
    html += '</tbody></table>';
    return html;
  }
}
