/**
 * Service to connect directly with the Gemini REST API.
 */

export class GeminiService {
  static LOCAL_STORAGE_KEY = 'gemini_api_key';

  /**
   * Retrieves the saved Gemini API key from LocalStorage.
   * @returns {string} The saved API key.
   */
  static getApiKey() {
    return localStorage.getItem(this.LOCAL_STORAGE_KEY) || '';
  }

  /**
   * Saves the Gemini API key to LocalStorage.
   * @param {string} key The API key to save.
   */
  static saveApiKey(key) {
    localStorage.setItem(this.LOCAL_STORAGE_KEY, key.trim());
  }

  /**
   * Generates a detailed HR Analytics report based on dataset statistics.
   * @param {Object} summary Statistical summary of the dataset.
   * @param {string} apiKey Gemini API Key.
   * @returns {Promise<string>} The markdown report generated by Gemini.
   */
  static async generateReport(summary, apiKey) {
    if (!apiKey) throw new Error('Gemini API key is required. Please set it in the Settings.');

    const cleanSummary = this.prepareCleanSummary(summary);
    
    const prompt = `Bạn là chuyên gia HR Analytics.
Hãy phân tích dữ liệu này và viết báo cáo chuyên nghiệp.

Dưới đây là bảng thống kê tổng hợp về dữ liệu nhân viên của công ty:
${JSON.stringify(cleanSummary, null, 2)}

Báo cáo phân tích phải bao gồm đầy đủ các mục sau và được định dạng Markdown đẹp mắt:
1. Executive Summary
2. Key Findings
3. Department Analysis
4. Salary Analysis
5. Employee Performance
6. Training Effectiveness
7. Promotion Analysis
8. Engagement Analysis
9. Risk Analysis
10. Recommendations`;

    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: {
              temperature: 0.2,
              topK: 40,
              topP: 0.95,
              maxOutputTokens: 8192,
            }
          }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error?.message || 'Error communicating with Gemini API.');
      }

      const result = await response.json();
      return result.candidates[0].content.parts[0].text;
    } catch (error) {
      console.error('Failed to generate report:', error);
      throw error;
    }
  }

  /**
   * Handles user queries regarding the HR dataset.
   * @param {Object} summary Statistical summary of the dataset.
   * @param {string} question The user's prompt/question.
   * @param {Array} history Conversation history: [{role: 'user'|'model', text: string}].
   * @param {string} apiKey Gemini API Key.
   * @returns {Promise<string>} The answer.
   */
  static async askChat(summary, question, history, apiKey) {
    if (!apiKey) throw new Error('Gemini API key is required. Please set it in the Settings.');

    const cleanSummary = this.prepareCleanSummary(summary);

    // Format history for Gemini contents parameter: [{ role: "user" | "model", parts: [{ text: ... }] }]
    const formattedContents = [];
    
    // Push history
    history.forEach(msg => {
      formattedContents.push({
        role: msg.role === 'user' ? 'user' : 'model',
        parts: [{ text: msg.text }]
      });
    });

    // Add current query with context instructions prepended to help Gemini answer based on the summary.
    const contextPrompt = `Bạn là một trợ lý ảo HR Analytics thông minh và chuyên nghiệp. Bạn được cung cấp dữ liệu thống kê nhân sự sau:
${JSON.stringify(cleanSummary, null, 2)}

Hãy trả lời câu hỏi sau của người dùng dựa trên dữ liệu trên. 
Nếu họ hỏi về các chỉ số không có trong bảng thống kê, hãy lịch sự giải thích. 
Hãy trả lời bằng tiếng Việt, ngắn gọn, có cấu trúc rõ ràng và dễ hiểu.

Câu hỏi của người dùng: "${question}"`;

    formattedContents.push({
      role: 'user',
      parts: [{ text: contextPrompt }]
    });

    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: formattedContents,
            generationConfig: {
              temperature: 0.4,
              maxOutputTokens: 2048,
            }
          }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error?.message || 'Error communicating with Gemini API.');
      }

      const result = await response.json();
      return result.candidates[0].content.parts[0].text;
    } catch (error) {
      console.error('Failed to get chat response:', error);
      throw error;
    }
  }

  /**
   * Helper to reduce the summary payload size so we don't hit payload limits and make calls fast.
   */
  static prepareCleanSummary(summary) {
    return {
      totalEmployees: summary.totalEmployees,
      totalDepartments: summary.totalDepartments,
      averageSalary: Math.round(summary.averageSalary),
      averageAge: Math.round(summary.averageAge * 10) / 10,
      averageTenure: Math.round(summary.averageTenure * 10) / 10,
      averagePerformance: Math.round(summary.averagePerformance * 10) / 10,
      averageEngagement: Math.round(summary.averageEngagement * 10) / 10,
      totalTrainingHours: summary.totalTrainingHours,
      totalAbsenceDays: summary.totalAbsenceDays,
      totalPromotions: summary.totalPromotions,
      
      topDepartmentStats: {
        highestAverageSalary: {
          department: summary.topDeptSalary?.name,
          average: Math.round(summary.topDeptSalary?.val || 0)
        },
        highestAveragePerformance: {
          department: summary.topDeptPerformance?.name,
          average: Math.round((summary.topDeptPerformance?.val || 0) * 10) / 10
        },
        highestEngagement: {
          department: summary.highestEngagementDept?.name,
          average: Math.round((summary.highestEngagementDept?.val || 0) * 10) / 10
        },
        highestAbsence: {
          department: summary.highestAbsenceDept?.name,
          average: Math.round((summary.highestAbsenceDept?.val || 0) * 10) / 10
        }
      },

      genderDistribution: summary.genderDistribution,
      ageDistribution: summary.ageDistribution,
      performanceDistribution: summary.performanceDistribution,
      engagementDistribution: summary.engagementDistribution,

      departmentBreakdown: summary.salaryBoxPlot.map(dept => {
        const training = summary.trainingHoursByDept.find(t => t.department === dept.department);
        const absences = summary.absencesByDept.find(a => a.department === dept.department);
        const promo = summary.promotionsByDept.find(p => p.department === dept.department);
        const count = summary.deptCounts[summary.departments.indexOf(dept.department)];

        return {
          department: dept.department,
          employeeCount: count,
          averageSalary: Math.round(dept.average),
          salaryRange: { min: dept.boxValues[0], max: dept.boxValues[4] },
          averagePerformance: Math.round((summary.performanceDistribution[5] ? 4 : 3) * 10) / 10, // approximate or just omit if raw not stored
          totalTrainingHours: training?.total || 0,
          averageTrainingHours: Math.round((training?.average || 0) * 10) / 10,
          totalAbsenceDays: absences?.total || 0,
          averageAbsenceDays: Math.round((absences?.average || 0) * 10) / 10,
          totalPromotions: promo?.total || 0
        };
      }),

      correlations: summary.correlationKeys.map((key, i) => {
        // Return strongest correlation for each variable
        const related = summary.correlationMatrix
          .filter(cell => cell[1] === i && cell[0] !== i)
          .map(cell => ({
            variable: summary.correlationKeys[cell[0]],
            coefficient: cell[2]
          }))
          .sort((a, b) => Math.abs(b.coefficient) - Math.abs(a.coefficient))[0];
        
        return {
          variable: key,
          strongestCorrelatedWith: related ? related.variable : 'None',
          correlationCoefficient: related ? related.coefficient : 0
        };
      })
    };
  }
}
